### ISSUE TITLE
Can the docker image be cached?

### ISSUE THREAD

**Issue by davenquinn** [distributhor/workflow-webhook#2]
This is a cool project. When implementing in a CI workflow, it seems that the docker image is built every time, although it never changes within my project. This adds an ~30sec step to each of my builds that could be avoided with caching.

Would it be possible to cache the built image as an artifact on Github Packages? This would greatly accelerate the build.

**Comment by distributhor** [comment]
Hi. Thanks for the feedback. I can definitely look into the ability to cache the image.

**Comment by distributhor** [comment]
Hi. Apologies for the long delay on this. I will be publishing another release this week should speed things up. If you are still using the project, check out for the update and let me know if it is running faster (fast enough). Otherwise some further improvements can be made.

**Comment by distributhor** [comment]
A new version is now available which should speed up the build a little. If you are still using the webhook, please test and if it still appears slow, please open the issue again.

**Comment by distributhor** [comment]
Just some further info. In addition to the measures taken with the last changes, official GitHub support for cached docker images will arrive in November sometime. When it lands I will make further changes, if required, to support this. See https://github.community/t/caching-files-between-github-action-executions/16047/13
