### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by austins** [distributhor/workflow-webhook#26]
I was getting a 403 error in the log. I thought this was because I had my web server only accept POST, but even with GET enabled, I still get the 403 error. It looks like it's doing a POST in any case. Turns out this is because the User-Agent header has duplicate text in it, which causes some web servers to block the request.

**Comment by austins** [comment]
PR submitted: https://github.com/distributhor/workflow-webhook/pull/27

**Comment by distributhor** [comment]
Thanks for picking this up. Merged. Will be doing a release, along with some other additional features and improvements over the weekend.
