### ISSUE TITLE
Request ID does not show in action logs

### ISSUE THREAD

**Issue by lukep-coxauto** [distributhor/workflow-webhook#28]
The webhook generates a requestId property in the body of the payload.  This is great because it could be used to correlate the request in the system that is processing the webhook call.  However, this requestId is not logged from `workflow-webhook`.

My suggestion is to log requestId (if not in `silent` mode) so that you can look at the Actions run to get the requestId and then correlate it to the invoked system's logs.

**Comment by distributhor** [comment]
Thanks for the feedback. Definitely something that can be done. I'll have a look soon-ish, just away at the moment.

**Comment by distributhor** [comment]
Back after some extended time off. Just a quick note that I will pick up this issue sometime this week or next.

**Comment by distributhor** [comment]
Busy testing and viewing the logs, and will prepare a release with this change soon

**Comment by lukep-coxauto** [comment]
Great, thanks!

**Comment by distributhor** [comment]
Done with local testing. I've created a "v2.0.3" tag under which it's already available for use, but haven't updated the "latest" tag to this version yet. Going to test this for a day or two in a production environment before updating the "latest" tag and making an official release. Once I confirm that it's fine in our production environment, using the built docker image, then I'll do a proper version release. Apologies for the long turn-around time on this.

**Comment by distributhor** [comment]
I could probably just release, it's such a minor change, but I'm conservative about pushing any changes that other's depend on in production So want to tick all the boxes.

**Comment by distributhor** [comment]
Version released and "v2" tag updated to point to new image
