### ISSUE TITLE
Support for Self-Signed SSL Certificates

### ISSUE THREAD

**Issue by yasithab** [distributhor/workflow-webhook#3]
Hello,

I have a Jenkins server which is configured to use a Self-Signed SSL certificate. When I try to trigger a Jenkins Job using this action, it is failing due to the following error. Is it possible to override SSL validation?

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it.
To learn more about this situation and how to fix it, please visit the web page mentioned above.
```

**Comment by distributhor** [comment]
Hi. I am currently away on holiday. Will have a look at this when I'm back in September.

**Comment by distributhor** [comment]
Hi. Apologies for the long delay on this. I have moved countries in the last two months, so many things was on pause. I am now looking into addressing a few issues and requests. This is an easy fix and will be in the next release this coming week.

**Comment by distributhor** [comment]
There is now a new version which should address this. If you are still using the webhook, feel free to test and if the problem still persists you can open a new issue.
