### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by sudara** [distributhor/workflow-webhook#30]
Hi there,

I'm integrating this action (thanks!) but noticed since my endpoint isn't quite ready, that the action takes 2 minutes to fail.

> curl: (28) Failed to connect to mydomain.com port 443 after 130061 ms: Operation timed out

Would you be open to adding an option for `--connect-timeout` with a friendly default of 10 seconds? That would help save time/expense when developing workflows...

**Comment by distributhor** [comment]
Hi. Thanks for the feedback. I'll be adding the option soon, probably within the next week or so.

**Comment by distributhor** [comment]
Released a new version (v2.0.4) which supports the configuration of a timeout value. The v2 tag now also points to this latest version.
