### ISSUE TITLE
make webhook_secret optional

### ISSUE THREAD

**Issue by MentalGear** [distributhor/workflow-webhook#31]
Use-case if the webhook already has a "password" in the URL.

**Comment by distributhor** [comment]
I'll be looking into the requested features soon.

**Comment by distributhor** [comment]
I am looking at feature requests this week. Could you please elaborate a bit more on the use case. The secret is typically configured in Github, and used to sign the call. Are you suggesting that there is a use case in which the URL called (the webhook itself) has a password embedded? Or am I misunderstanding?

**Comment by MentalGear** [comment]
Sure! For example: Pipedream uses random URL path as triggers for Webhooks.

Since it's a unique sequence of random numbers and meant to be kept private, the url is the password at the same time.

**Comment by distributhor** [comment]
Thanks, that's a helpful insight. In short, if one makes the secret optional, the default behaviour could be to then use the URL itself instead as the value used for the digest. Would that satisfy the requirement from your perspective?

**Comment by MentalGear** [comment]
Absolutely, only the URL as mandatory parameter would be satisfy !

**Comment by distributhor** [comment]
Feature tested and released on v3.0.1

**Comment by MentalGear** [comment]
Thanks for your work !
