### ISSUE TITLE
Support file uploads

### ISSUE THREAD

**Issue by asmeurer** [distributhor/workflow-webhook#32]
I want to write an action that produces data that gets submitted to a webhook by workflows, but the data in general is too large to put in an action output (GitHub Actions produces an "out of memory" error). It would be useful to be able to upload a file to the webhook. I believe this can be done with curl using the `-F` flag (see https://everything.curl.dev/http/multipart#file-input).

**Comment by distributhor** [comment]
I'll have a look at this option and how it can be incorporated

**Comment by distributhor** [comment]
Hi. I am trying to understand the use case you have. Currently the call to the webhook will post some data to it (either JSON or form urlencoded). The file would presumably be generated by the GIthub action when it's run? And then it must be sent as an additional input along with the current data? If you can elaborate a bit it will help me determine the best course of action.

**Comment by asmeurer** [comment]
I'll prefix this by saying I'm not an expert at GitHub Actions, so it's quite possible there's a better way to do what I'm trying to do.

We are trying to build a reusable Action that people can run that will run a test suite and upload the results (as a JSON file) to a server. This JSON file can be large (~10 MB) as it contains information about all the tests, especially if there are many test failures. The way I am implementing this is to have a reusable action repo, which is a composite action) that has all the logic for running the tests, getting the JSON file, etc. Then the users who will run this action will create a action file that references this action and gives it the appropriate inputs.  Unfortunately, as far as I can tell, the actual workflow-webhook part of the action has to go in this end-user workflow file, because if you put it in the composite action, it cannot access the secret variables (which would be different for each workflow). Ideally I'd like to make the logic that goes in the workflow files as minimal as possible so that if we need to update the composite action we won't have to go and update very individual workflow file. 

My initial attempt was to send the JSON blob through as an output of the composite action, but this failed because GitHub Actions gave a "maximum allowed memory size was exceeded" error.

**Comment by ranma2913** [comment]
you could just have a shell step where you run your own CURL commands like this action does:

```yaml
# initial workflow steps
- name: Upload Json
  shell: bash
  run: |
    curl -X POST "https://myhost.com/my/path" --data "@path/of/file.json"
# later workflow steps
```
