### ISSUE TITLE
curl: option -: is unknown

### ISSUE THREAD

**Issue by jainr** [distributhor/workflow-webhook#35]
Run distributhor/workflow-webhook@v3.0.1
/usr/bin/docker run --name ghcriodistributhorworkflowwebhookcontainerv301_3[7]--workdir /github/workspace --rm -e "webhook_url" -e "webhook_secret" -e "INPUT_WEBHOOK_URL" -e "INPUT_WEBHOOK_SECRET" -e "INPUT_WEBHOOK_AUTH" -e "INPUT_WEBHOOK_TYPE" -e "INPUT_VERBOSE" -e "INPUT_SILENT" -e "INPUT_TIMEOUT" -e "INPUT_VERIFY_SSL" -e "INPUT_EVENT_NAME" -e "INPUT_DATA" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/feathr/feathr":"/github/workspace" ghcr.io/distributhor/workflow-webhook-container:v3.0.1
Webhook Request ID: 402485ab-f1cd-4cab-bf7f-b6c4f14d55b0
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by distributhor** [comment]
Hi. Just want to confirm, is the issue now sorted?

**Comment by jainr** [comment]
Yes, I was using a wrong URL for webhook and it was throwing Curl error, it was an error on my side.
