### ISSUE TITLE
Allow for data value that is not JSON

### ISSUE THREAD

**Issue by paulyhedral** [distributhor/workflow-webhook#4]
I have a webhook I need to call that does not accept JSON, only form data. Is it possible to provide a `data` value that is not JSON?

**Comment by distributhor** [comment]
Hi. I a currently away on holiday. Will have a look at this when I'm back in September.

**Comment by distributhor** [comment]
Hi. Just getting back to resolving some requests and issues on the project now. I am going to see if I can make form data work as part of the efforts.

**Comment by distributhor** [comment]
I have released a new version today (v1.0.4) that has some basic support for urlencoded form data. It may or may not be exactly what you need. I will close the issue, but welcome any further suggestions for improvement if required. I've done some basic testing, but admittedly it's not been wide test coverage. I created a simple endpoint on my side that would accept the data and checked that I could access it, but in more extensive usage some minor issues may still pop - especially regarding special characters that are potentially not handled correctly in the POSTed data.

**Comment by distributhor** [comment]
I have made an update to the release that now correctly encodes all POSTed data
