### ISSUE TITLE
bug: multiline responses cause an error 'Unable to process file command'

### ISSUE THREAD

**Issue by jromero** [distributhor/workflow-webhook#40]
Latest [feature of returning the results to `output`](https://github.com/distributhor/workflow-webhook/blob/6684d6301159d8c6e1c6527f78d4db9b5d8e5fed/entrypoint.sh#L127) introduced a failure when there's a multiline response in [v3.0.2](https://github.com/distributhor/workflow-webhook/releases/tag/v3.0.2).

As per [this discussion](https://stackoverflow.com/q/74137120/552902) and the [official docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings), multiline responses need to be handled accordingly.

### Expected

Action to complete successfully.

### Received

```log
Webhook Request ID: a7c49923-05c1-4b44-8f8c-2aa661dc9ef5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
...

Error: Unable to process file command 'output' successfully.
Error: Invalid format '***'
```

**Comment by distributhor** [comment]
Apologies for the late reply on this. I somehow missed this notification. I'll will have a look at it this week.

**Comment by mshogren** [comment]
I was having the issue but it is fixed for me now
