### ISSUE TITLE
response-body not showing when error encountered

### ISSUE THREAD

**Issue by swichers** [distributhor/workflow-webhook#46]
If the endpoint returns an error status (like 500) then no response body is shown. If I manually hit the endpoint with the same data, I get an expected error message describing the problem with the payload.

The expectation here is that if there is response data and verbose is on, then I should see the response data even if the server returned a non-200 code.

(note: originally this issue was about it not showing in general. What was actually happening is that this other issue was making it seem like there was a general problem)

**Comment by distributhor** [comment]
Will see if I can take a look at this today

**Comment by distributhor** [comment]
Busy debugging a small issue with the required change, which I can hopefully resolve soon

**Comment by distributhor** [comment]
You are welcome to test this now, v3.0.5 released
